/*
    ./js/BandwidthTest.js
    Created 25/05/2018 at 10:38:31 from:
        Messages = msgtools/parser/test/messages//BandwidthTest.yaml
        Template = Template.js
        Language = javascript

                     AUTOGENERATED FILE, DO NOT EDIT

*/
//import { NetworkHeader } from '../headers/NetworkHeader.js'
//import MessageDictionary from '../MessageDictionary.js'

var BandwidthTest = function(buffer) {
    // have baseclass construct the buffer?
    //Message.call(this, MSG_SIZE);
        
    if (buffer==undefined)
    {
        buffer = new ArrayBuffer(NetworkHeader.prototype.MSG_SIZE+BandwidthTest.prototype.MSG_SIZE);
        this.m_data = new DataView(buffer, NetworkHeader.prototype.MSG_SIZE);
        this.hdr = new NetworkHeader(buffer);
        this.hdr.SetMessageID(BandwidthTest.prototype.MSG_ID);
        this.hdr.SetDataLength(buffer.byteLength - NetworkHeader.prototype.MSG_SIZE);
        //this.InitializeTime();
        this.Init();
    }
    else
    {
        this.m_data = new DataView(buffer, NetworkHeader.prototype.MSG_SIZE);
        this.hdr = new NetworkHeader(buffer);
    }
};

// This is for 0.28.42/Messaging.js compatibility
if (typeof(MessageDictionary)!=='undefined' && MessageDictionary != null)
    // add our class to the dictionary
    MessageDictionary[13] = BandwidthTest

// This is for 0.29.42/msgtools.js compatibility
if (typeof msgtools === 'object')
    msgtools.registerMessage(13,BandwidthTest)

// how to make constants?
BandwidthTest.prototype.MSG_ID = 13;
BandwidthTest.prototype.MSG_SIZE = 121;
BandwidthTest.prototype.MSG_NAME = "s.BandwidthTest";

BandwidthTest.prototype.MsgName = function(){
    return "s.BandwidthTest";
}

BandwidthTest.prototype.Init = function(){
};


// http://stackoverflow.com/a/130572
// SequenceNumber , (0 to 255)
BandwidthTest.prototype.GetSequenceNumber = function()
{
    var value = (this.m_data.getUint8(0));
    return value;
};
// Any relevant test data, such as timestamps. , (0 to 4294967295)
BandwidthTest.prototype.GetTestData = function(idx)
{
    var value = (this.m_data.getUint32(1+idx*4));
    return value;
};
// SequenceNumber , (0 to 255)
BandwidthTest.prototype.SetSequenceNumber = function(value)
{
    this.m_data.setUint8(0, value);
};
// Any relevant test data, such as timestamps. , (0 to 4294967295)
BandwidthTest.prototype.SetTestData = function(value, idx)
{
    this.m_data.setUint32(1+idx*4, value);
};

// Convert to a javascript object
BandwidthTest.prototype.toObject = function(){
    ret = {};
    try { ret["SequenceNumber"] = this.GetSequenceNumber(); } catch (err) {}
    try { ret["TestData"] = []; } catch (err) {}
    try { 
        for(i=0; i<30; i++)
            ret["TestData"][i] = this.GetTestData(i);
    } catch (err) {}
    return ret;
}

// Reflection information
BandwidthTest.prototype.fields = [
    {name:"SequenceNumber",type:"int",units:"",minVal:"0",maxVal:"255",description:"SequenceNumber",get:"GetSequenceNumber",set:"SetSequenceNumber",count:1, bitfieldInfo : [], enumLookup : []},
    {name:"TestData",type:"int",units:"",minVal:"0",maxVal:"4294967295",description:"Any relevant test data, such as timestamps.",get:"GetTestData",set:"SetTestData",count:30, bitfieldInfo : [], enumLookup : []}
]

// for react-native and node.js, we should set module.exports so our class can be accessed externally
if(typeof module != 'undefined' && typeof module.exports != 'undefined')
    module.exports.BandwidthTest = BandwidthTest;
