/*
    ./js/Printf.js
    Created 25/05/2018 at 10:38:31 from:
        Messages = msgtools/parser/test/messages//Printf.yaml
        Template = Template.js
        Language = javascript

                     AUTOGENERATED FILE, DO NOT EDIT

*/
//import { NetworkHeader } from '../headers/NetworkHeader.js'
//import MessageDictionary from '../MessageDictionary.js'

var Printf = function(buffer) {
    // have baseclass construct the buffer?
    //Message.call(this, MSG_SIZE);
        
    if (buffer==undefined)
    {
        buffer = new ArrayBuffer(NetworkHeader.prototype.MSG_SIZE+Printf.prototype.MSG_SIZE);
        this.m_data = new DataView(buffer, NetworkHeader.prototype.MSG_SIZE);
        this.hdr = new NetworkHeader(buffer);
        this.hdr.SetMessageID(Printf.prototype.MSG_ID);
        this.hdr.SetDataLength(buffer.byteLength - NetworkHeader.prototype.MSG_SIZE);
        //this.InitializeTime();
        this.Init();
    }
    else
    {
        this.m_data = new DataView(buffer, NetworkHeader.prototype.MSG_SIZE);
        this.hdr = new NetworkHeader(buffer);
    }
};

// This is for 0.28.42/Messaging.js compatibility
if (typeof(MessageDictionary)!=='undefined' && MessageDictionary != null)
    // add our class to the dictionary
    MessageDictionary[255] = Printf

// This is for 0.29.42/msgtools.js compatibility
if (typeof msgtools === 'object')
    msgtools.registerMessage(255,Printf)

// how to make constants?
Printf.prototype.MSG_ID = 255;
Printf.prototype.MSG_SIZE = 128;
Printf.prototype.MSG_NAME = "s.Printf";

Printf.prototype.MsgName = function(){
    return "s.Printf";
}

Printf.prototype.Init = function(){
};


// http://stackoverflow.com/a/130572
// Some sort of identifier for the thread printing the message. PlatformSpecific, (0 to 4294967295)
Printf.prototype.GetThreadID = function()
{
    var value = (this.m_data.getUint32(0));
    return value;
};
// The line number that caused the message to appear. NA, (0 to 4294967295)
Printf.prototype.GetLineNumber = function()
{
    var value = (this.m_data.getUint32(4));
    return value;
};
// The string to display. ASCII, (0 to 255)
Printf.prototype.GetBuffer = function(idx)
{
    var value = (this.m_data.getUint8(8+idx*1));
    return value;
};
// The string to display. ASCII, (0 to 255)
Printf.prototype.GetBufferString = function()
{
    var value = '';
    for(i=0; i<120 && i<this.hdr.GetDataLength()-8; i++)
    {
        nextChar = String.fromCharCode(this.GetBuffer(i));
        if(nextChar == '\0')
            break;
        value += nextChar;
    }
    return value;
};
// Some sort of identifier for the thread printing the message. PlatformSpecific, (0 to 4294967295)
Printf.prototype.SetThreadID = function(value)
{
    this.m_data.setUint32(0, value);
};
// The line number that caused the message to appear. NA, (0 to 4294967295)
Printf.prototype.SetLineNumber = function(value)
{
    this.m_data.setUint32(4, value);
};
// The string to display. ASCII, (0 to 255)
Printf.prototype.SetBuffer = function(value, idx)
{
    this.m_data.setUint8(8+idx*1, value);
};
// The string to display. ASCII, (0 to 255)
Printf.prototype.SetBufferString = function(value)
{
    for(i=0; i<120 && i<value.length; i++)
    {
        this.SetBuffer(value[i].charCodeAt(0), i);
    }
};

// Convert to a javascript object
Printf.prototype.toObject = function(){
    ret = {};
    try { ret["ThreadID"] = this.GetThreadID(); } catch (err) {}
    try { ret["LineNumber"] = this.GetLineNumber(); } catch (err) {}
    try { ret["Buffer"] = this.GetBufferString(); } catch (err) {}
    return ret;
}

// Reflection information
Printf.prototype.fields = [
    {name:"ThreadID",type:"int",units:"PlatformSpecific",minVal:"0",maxVal:"4294967295",description:"Some sort of identifier for the thread printing the message.",get:"GetThreadID",set:"SetThreadID",count:1, bitfieldInfo : [], enumLookup : []},
    {name:"LineNumber",type:"int",units:"NA",minVal:"0",maxVal:"4294967295",description:"The line number that caused the message to appear.",get:"GetLineNumber",set:"SetLineNumber",count:1, bitfieldInfo : [], enumLookup : []},
    {name:"Buffer",type:"string",units:"ASCII",minVal:"0",maxVal:"255",description:"The string to display.",get:"GetBufferString",set:"SetBufferString",count:1, bitfieldInfo : [], enumLookup : []}
]

// for react-native and node.js, we should set module.exports so our class can be accessed externally
if(typeof module != 'undefined' && typeof module.exports != 'undefined')
    module.exports.Printf = Printf;
