/*
    <OUTPUTFILENAME>
    Created <DATE> from:
        Messages = <INPUTFILENAME>
        Template = <TEMPLATEFILENAME>
        Language = <LANGUAGEFILENAME>

                     AUTOGENERATED FILE, DO NOT EDIT

*/
var <MSGNAME> = function(buffer) {
    // have baseclass construct the buffer?
    //Message.call(this, MSG_SIZE);
    
    // how to make constants?
    this.MSG_SIZE = <MSGSIZE>;
    
    if (buffer==undefined)
    {
        var buffer = new ArrayBuffer(this.MSG_SIZE);
        this.m_data = new DataView(buffer);
    }
    else
    {
        this.m_data = new DataView(buffer);
    }

    //this.InitializeTime();
    this.Init();
};

<MSGNAME>.prototype.Init = function(){
    <INIT_CODE>
};


// http://stackoverflow.com/a/130572
<ENUMERATIONS>
<ACCESSORS>
<MSGNAME>.prototype.SetMessageID = function(value){
    <SETMSGID>;
};
<MSGNAME>.prototype.GetMessageID = function(){
    return <GETMSGID>;
};
