#    <OUTPUTFILENAME>
#    Created <DATE> from:
#        Messages = <INPUTFILENAME>
#        Template = <TEMPLATEFILENAME>
#        Language = <LANGUAGEFILENAME>
#
#                     AUTOGENERATED FILE, DO NOT EDIT
import struct
import ctypes
from Messaging import *
import Messaging as msg

class <MSGNAME> :
    SIZE = <MSGSIZE>
    MSG_OFFSET = 0
    # Enumerations
    <ENUMERATIONS>

    @staticmethod
    def Create() :
        message_buffer = ctypes.create_string_buffer(<MSGNAME>.SIZE)
        <INIT_CODE>
        return message_buffer

    @staticmethod
    def MsgName():
        return "<MSGNAME>"
    # Accessors
    <ACCESSORS>

    # Reflection information
    fields = [ \
        <REFLECTION>\
    ]
