#    <OUTPUTFILENAME>
#    Created <DATE> from:
#        Messages = <INPUTFILENAME>
#        Template = <TEMPLATEFILENAME>
#        Language = <LANGUAGEFILENAME>
#
#                     AUTOGENERATED FILE, DO NOT EDIT
import struct
import ctypes
from Messaging import Messaging
import Messaging as msg

class <MSGNAME> :
    SIZE = <MSGSIZE>
    MSG_OFFSET = 0
    FIELDINFOS = <FIELDINFOS>

    @staticmethod
    def set(bytearray, fieldInfo, value, index=1):
        if(fieldInfo["Units"] != "ASCII"):
            value = int(value)
        if(fieldInfo["Count"] == 1):
            getattr(<MSGNAME>, fieldInfo["Set"])(bytearray, value)
        else:
            getattr(<MSGNAME>, fieldInfo["Set"])(bytearray, value, index)

    @staticmethod
    def get(bytearray, fieldInfo, index=1):
        if(fieldInfo["Count"] == 1):
            value = getattr(<MSGNAME>, fieldInfo["Get"])(bytearray)
        else:
            value = getattr(<MSGNAME>, fieldInfo["Get"])(bytearray, index)
        return value

    @staticmethod
    def Create() :
        bytes = ctypes.create_string_buffer(<MSGNAME>.SIZE)
        <INIT_CODE>
        return bytes

    @staticmethod
    def MsgName():
        return "<MSGNAME>"
    # Enumerations
    <ENUMERATIONS>
    # Accessors
    <ACCESSORS>
