#    <OUTPUTFILENAME>
#    Created <DATE> from:
#        Messages = <INPUTFILENAME>
#        Template = <TEMPLATEFILENAME>
#        Language = <LANGUAGEFILENAME>
#
#                     AUTOGENERATED FILE, DO NOT EDIT
import struct
import ctypes
from Messaging import *
import Messaging as msg

class <MSGNAME> :
    SIZE = <MSGSIZE>
    MSG_OFFSET = 0
    fields = []
    fields.append(<FIELDINFOS>)

    @staticmethod
    def set(message_buffer, fieldInfo, value, index=1):
        Messaging.set(<MSGNAME>, message_buffer, fieldInfo, value, index)

    @staticmethod
    def get(message_buffer, fieldInfo, index=1):
        return Messaging.get(<MSGNAME>, message_buffer, fieldInfo, index)

    @staticmethod
    def Create() :
        message_buffer = ctypes.create_string_buffer(<MSGNAME>.SIZE)
        <INIT_CODE>
        return message_buffer

    @staticmethod
    def MsgName():
        return "<MSGNAME>"
    # Enumerations
    <ENUMERATIONS>
    # Accessors
    <ACCESSORS>
