/*
    ./js/headers/CANHeader.js
    Created 25/05/2018 at 10:38:31 from:
        Messages = msgtools/parser/test/messages//headers/CANHeader.yaml
        Template = HeaderTemplate.js
        Language = javascript

                     AUTOGENERATED FILE, DO NOT EDIT

*/
var CANHeader = function(buffer) {
    // have baseclass construct the buffer?
    //Message.call(this, MSG_SIZE);
        
    if (buffer==undefined)
    {
        buffer = new ArrayBuffer(CANHeader.prototype.MSG_SIZE);
        this.m_data = new DataView(buffer);
        this.Init();
    }
    else
    {
        this.m_data = new DataView(buffer);
    }
};

// how to make constants?
CANHeader.prototype.MSG_SIZE = 7;
CANHeader.prototype.MSG_NAME = "s/headers.CANHeader";

CANHeader.prototype.Init = function(){
    this.SetSource(0);
    this.SetDestination(0);
    this.SetID(0);
    this.SetLength(0);
    this.SetPriority(0);
};


// http://stackoverflow.com/a/130572
//  , (0 to 255)
CANHeader.prototype.GetSource = function()
{
    var value = (this.m_data.getUint8(0));
    return value;
};
//  , (0 to 255)
CANHeader.prototype.GetDestination = function()
{
    var value = (this.m_data.getUint8(1));
    return value;
};
//  , (0 to 65535)
CANHeader.prototype.GetID = function()
{
    var value = (this.m_data.getUint16(2));
    return value;
};
//  , (0 to 65535)
CANHeader.prototype.GetLength = function()
{
    var value = (this.m_data.getUint16(4));
    return value;
};
//  , (0 to 255)
CANHeader.prototype.GetPriority = function()
{
    var value = (this.m_data.getUint8(6));
    return value;
};
//  , (0 to 255)
CANHeader.prototype.SetSource = function(value)
{
    this.m_data.setUint8(0, value);
};
//  , (0 to 255)
CANHeader.prototype.SetDestination = function(value)
{
    this.m_data.setUint8(1, value);
};
//  , (0 to 65535)
CANHeader.prototype.SetID = function(value)
{
    this.m_data.setUint16(2, value);
};
//  , (0 to 65535)
CANHeader.prototype.SetLength = function(value)
{
    this.m_data.setUint16(4, value);
};
//  , (0 to 255)
CANHeader.prototype.SetPriority = function(value)
{
    this.m_data.setUint8(6, value);
};
CANHeader.prototype.SetMessageID = function(id){
    this.SetID(id & 0xffff);
};
CANHeader.prototype.GetMessageID = function(){
    return this.GetID();
};

// Convert to a javascript object
CANHeader.prototype.toObject = function(){
    ret = {};
    try { ret["Source"] = this.GetSource(); } catch (err) {}
    try { ret["Destination"] = this.GetDestination(); } catch (err) {}
    try { ret["ID"] = this.GetID(); } catch (err) {}
    try { ret["Length"] = this.GetLength(); } catch (err) {}
    try { ret["Priority"] = this.GetPriority(); } catch (err) {}
    return ret;
}

// for react-native and node.js, we should set module.exports so our class can be accessed externally
if(typeof module != 'undefined' && typeof module.exports != 'undefined')
    module.exports.CANHeader = CANHeader;
