/*
    ./js/Network/Connect.js
    Created 25/05/2018 at 10:38:31 from:
        Messages = msgtools/parser/test/messages//Network/Connect.yaml
        Template = Template.js
        Language = javascript

                     AUTOGENERATED FILE, DO NOT EDIT

*/
//import { NetworkHeader } from '../headers/NetworkHeader.js'
//import MessageDictionary from '../MessageDictionary.js'

var Connect = function(buffer) {
    // have baseclass construct the buffer?
    //Message.call(this, MSG_SIZE);
        
    if (buffer==undefined)
    {
        buffer = new ArrayBuffer(NetworkHeader.prototype.MSG_SIZE+Connect.prototype.MSG_SIZE);
        this.m_data = new DataView(buffer, NetworkHeader.prototype.MSG_SIZE);
        this.hdr = new NetworkHeader(buffer);
        this.hdr.SetMessageID(Connect.prototype.MSG_ID);
        this.hdr.SetDataLength(buffer.byteLength - NetworkHeader.prototype.MSG_SIZE);
        //this.InitializeTime();
        this.Init();
    }
    else
    {
        this.m_data = new DataView(buffer, NetworkHeader.prototype.MSG_SIZE);
        this.hdr = new NetworkHeader(buffer);
    }
};

// This is for 0.28.42/Messaging.js compatibility
if (typeof(MessageDictionary)!=='undefined' && MessageDictionary != null)
    // add our class to the dictionary
    MessageDictionary[4294967041] = Connect

// This is for 0.29.42/msgtools.js compatibility
if (typeof msgtools === 'object')
    msgtools.registerMessage(4294967041,Connect)

// how to make constants?
Connect.prototype.MSG_ID = 4294967041;
Connect.prototype.MSG_SIZE = 64;
Connect.prototype.MSG_NAME = "s/Network.Connect";

Connect.prototype.MsgName = function(){
    return "s/Network.Connect";
}

Connect.prototype.Init = function(){
};


// http://stackoverflow.com/a/130572
// The name of the client. ASCII, (0 to 255)
Connect.prototype.GetName = function(idx)
{
    var value = (this.m_data.getUint8(0+idx*1));
    return value;
};
// The name of the client. ASCII, (0 to 255)
Connect.prototype.GetNameString = function()
{
    var value = '';
    for(i=0; i<64 && i<this.hdr.GetDataLength()-0; i++)
    {
        nextChar = String.fromCharCode(this.GetName(i));
        if(nextChar == '\0')
            break;
        value += nextChar;
    }
    return value;
};
// The name of the client. ASCII, (0 to 255)
Connect.prototype.SetName = function(value, idx)
{
    this.m_data.setUint8(0+idx*1, value);
};
// The name of the client. ASCII, (0 to 255)
Connect.prototype.SetNameString = function(value)
{
    for(i=0; i<64 && i<value.length; i++)
    {
        this.SetName(value[i].charCodeAt(0), i);
    }
};

// Convert to a javascript object
Connect.prototype.toObject = function(){
    ret = {};
    try { ret["Name"] = this.GetNameString(); } catch (err) {}
    return ret;
}

// Reflection information
Connect.prototype.fields = [
    {name:"Name",type:"string",units:"ASCII",minVal:"0",maxVal:"255",description:"The name of the client.",get:"GetNameString",set:"SetNameString",count:1, bitfieldInfo : [], enumLookup : []}
]

// for react-native and node.js, we should set module.exports so our class can be accessed externally
if(typeof module != 'undefined' && typeof module.exports != 'undefined')
    module.exports.Connect = Connect;
