/*
    ./js/Network/StartLog.js
    Created 25/05/2018 at 10:38:31 from:
        Messages = msgtools/parser/test/messages//Network/StartLog.yaml
        Template = Template.js
        Language = javascript

                     AUTOGENERATED FILE, DO NOT EDIT

*/
//import { NetworkHeader } from '../headers/NetworkHeader.js'
//import MessageDictionary from '../MessageDictionary.js'

var StartLog = function(buffer) {
    // have baseclass construct the buffer?
    //Message.call(this, MSG_SIZE);
        
    if (buffer==undefined)
    {
        buffer = new ArrayBuffer(NetworkHeader.prototype.MSG_SIZE+StartLog.prototype.MSG_SIZE);
        this.m_data = new DataView(buffer, NetworkHeader.prototype.MSG_SIZE);
        this.hdr = new NetworkHeader(buffer);
        this.hdr.SetMessageID(StartLog.prototype.MSG_ID);
        this.hdr.SetDataLength(buffer.byteLength - NetworkHeader.prototype.MSG_SIZE);
        //this.InitializeTime();
        this.Init();
    }
    else
    {
        this.m_data = new DataView(buffer, NetworkHeader.prototype.MSG_SIZE);
        this.hdr = new NetworkHeader(buffer);
    }
};

// This is for 0.28.42/Messaging.js compatibility
if (typeof(MessageDictionary)!=='undefined' && MessageDictionary != null)
    // add our class to the dictionary
    MessageDictionary[4294967045] = StartLog

// This is for 0.29.42/msgtools.js compatibility
if (typeof msgtools === 'object')
    msgtools.registerMessage(4294967045,StartLog)

// how to make constants?
StartLog.prototype.MSG_ID = 4294967045;
StartLog.prototype.MSG_SIZE = 65;
StartLog.prototype.MSG_NAME = "s/Network.StartLog";

StartLog.prototype.MsgName = function(){
    return "s/Network.StartLog";
}

StartLog.prototype.Init = function(){
};


// http://stackoverflow.com/a/130572
StartLog.LogFileTypes = {};
StartLog.LogFileTypes["Binary"] = 0;
StartLog.LogFileTypes["JSON"] = 1;
StartLog.ReverseLogFileTypes = {};
for(key in StartLog.LogFileTypes) {
    StartLog.ReverseLogFileTypes[StartLog.LogFileTypes[key]] = key;
}

//  , (0 to 255)
StartLog.prototype.GetLogFileType = function(enumAsInt=false)
{
    var value = (this.m_data.getUint8(0));
    if(!enumAsInt)
    if(value in StartLog.ReverseLogFileTypes)
        value = StartLog.ReverseLogFileTypes[value];
    return value;
};
// The name of the log file.  Use default if unspecified. ASCII, (0 to 255)
StartLog.prototype.GetLogFileName = function(idx)
{
    var value = (this.m_data.getUint8(1+idx*1));
    return value;
};
// The name of the log file.  Use default if unspecified. ASCII, (0 to 255)
StartLog.prototype.GetLogFileNameString = function()
{
    var value = '';
    for(i=0; i<64 && i<this.hdr.GetDataLength()-1; i++)
    {
        nextChar = String.fromCharCode(this.GetLogFileName(i));
        if(nextChar == '\0')
            break;
        value += nextChar;
    }
    return value;
};
//  , (0 to 255)
StartLog.prototype.SetLogFileType = function(value)
{
    if(value in StartLog.LogFileTypes)
        value = StartLog.LogFileTypes[value];
    this.m_data.setUint8(0, value);
};
// The name of the log file.  Use default if unspecified. ASCII, (0 to 255)
StartLog.prototype.SetLogFileName = function(value, idx)
{
    this.m_data.setUint8(1+idx*1, value);
};
// The name of the log file.  Use default if unspecified. ASCII, (0 to 255)
StartLog.prototype.SetLogFileNameString = function(value)
{
    for(i=0; i<64 && i<value.length; i++)
    {
        this.SetLogFileName(value[i].charCodeAt(0), i);
    }
};

// Convert to a javascript object
StartLog.prototype.toObject = function(){
    ret = {};
    try { ret["LogFileType"] = this.GetLogFileType(); } catch (err) {}
    try { ret["LogFileName"] = this.GetLogFileNameString(); } catch (err) {}
    return ret;
}

// Reflection information
StartLog.prototype.fields = [
    {name:"LogFileType",type:"enumeration",units:"",minVal:"0",maxVal:"255",description:"",get:"GetLogFileType",set:"SetLogFileType",count:1, bitfieldInfo : [], enumLookup : [StartLog.LogFileTypes, StartLog.ReverseLogFileTypes]},
    {name:"LogFileName",type:"string",units:"ASCII",minVal:"0",maxVal:"255",description:"The name of the log file.  Use default if unspecified.",get:"GetLogFileNameString",set:"SetLogFileNameString",count:1, bitfieldInfo : [], enumLookup : []}
]

// for react-native and node.js, we should set module.exports so our class can be accessed externally
if(typeof module != 'undefined' && typeof module.exports != 'undefined')
    module.exports.StartLog = StartLog;
