/*
    <OUTPUTFILENAME>
    Created <DATE> from:
        Messages = <INPUTFILENAME>
        Template = <TEMPLATEFILENAME>
        Language = <LANGUAGEFILENAME>

                     AUTOGENERATED FILE, DO NOT EDIT

*/
#include <stdint.h>
#include <cfloat>
#include "FieldAccess.h"

class <MSGNAME>
{
    public:
        auto static constexpr SIZE = <MSGSIZE>;
        <MSGNAME>()
        {
            Init();
        }
        void Init()
        {
            <INIT_CODE>
        }
        <ENUMERATIONS>
        <FIELDINFOS>
        void SetMessageID(uint32_t id)
        {
            <SETMSGID>;
        }
        uint32_t GetMessageID()
        {
            return <GETMSGID>;
        }
        <ACCESSORS>
/*
        static MsgInfo* ReflectionInfo()
        {
            static bool firstTime = true;
            static MsgInfo msgInfo(-1, "<MSGNAME>", "<MSGDESCRIPTION>", SIZE);
            if(firstTime)
            {
                firstTime = false;
                msgInfo.AddField(new <REFLECTION>);
            }
            return &msgInfo;
        }
*/
    public:
        uint8_t m_data[SIZE];
};
