/*
    <OUTPUTFILENAME>
    Created <DATE> from:
        Messages = <INPUTFILENAME>
        Template = <TEMPLATEFILENAME>
        Language = <LANGUAGEFILENAME>

                     AUTOGENERATED FILE, DO NOT EDIT

*/
#include <stdint.h>
#include <cfloat>
#include "FieldAccess.h"

class <MSGNAME>
{
    const SIZE = <MSGSIZE>;
    ByteData _data;
    <MSGNAME>()
    {
        _data = new ByteData(SIZE);
        Init();
    }
    <MSGNAME>.fromBuffer(ByteBuffer buffer)
    {
        _data = ByteData.view(buffer);
    }
    void Init()
    {
        <INIT_CODE>
    }
    <ENUMERATIONS>
    <FIELDINFOS>
    void SetMessageID(uint32_t id)
    {
        <SETMSGID>;
    }
    uint32_t GetMessageID()
    {
        return <GETMSGID>;
    }
    <ACCESSORS>
/*
    static MsgInfo* ReflectionInfo()
    {
        static bool firstTime = true;
        static MsgInfo msgInfo(-1, "<MSGNAME>", "<MSGDESCRIPTION>", SIZE);
        if(firstTime)
        {
            firstTime = false;
            msgInfo.AddField(new <REFLECTION>);
        }
        return &msgInfo;
    }
*/
};
