/*
    <OUTPUTFILENAME>
    Created <DATE> from:
        Messages = <INPUTFILENAME>
        Template = <TEMPLATEFILENAME>
        Language = <LANGUAGEFILENAME>

                     AUTOGENERATED FILE, DO NOT EDIT

*/
import NetworkHeader from '../headers/NetworkHeader.js'
import MessageDictionary from '../MessageDictionary.js'

open class <MSGNAME>
{
    open let MSG_ID = <MSGID>;
    open let MSG_SIZE = <MSGSIZE>;
    open let MSG_NAME = "<MSGDESCRIPTOR>";
    var hdr;
    var m_data;
    open func init()
    {
        buffer = new ArrayBuffer(NetworkHeader.MSG_SIZE + MSG_SIZE);
        m_data = new DataView(buffer, NetworkHeader.MSG_SIZE);
        hdr = new NetworkHeader(buffer);
        hdr.SetMessageID(MSG_ID);
        hdr.SetDataLength(buffer.byteLength - NetworkHeader.MSG_SIZE);
        //InitializeTime();
        Init();
    }
    open func init(buffer: NSData)
    {
        m_data = new DataView(buffer, NetworkHeader.MSG_SIZE);
        hdr = new NetworkHeader(buffer);
    }
    func Init()
    {
        <INIT_CODE>
    }

    <ENUMERATIONS>
    <ACCESSORS>

    // Reflection information
    open let fields = [
        <REFLECTION>
    ]
};

// add our class to the dictionary
MessageDictionary[<MSGID>] = <MSGNAME>;
