%{
    <OUTPUTFILENAME>
    Created <DATE> from:
        Messages = <INPUTFILENAME>
        Template = <TEMPLATEFILENAME>
        Language = <LANGUAGEFILENAME>

                     AUTOGENERATED FILE, DO NOT EDIT

%}

classdef <MSGNAME>Message

    properties (Constant)
        MSG_ID = <MSGID>
        MSG_SIZE = <MSGSIZE>
        <ENUMERATIONS>
    end
    properties (hidden)
        % the buffer of data
        m_data
    end
    properties  (Dependent)
            <DECLARATIONS>
    end
    methods
        % create a message based on a data buffer
        function obj = <MSGNAME>Message(data)
            obj.m_data = data;
        end
        % create a new message (allocates a buffer for it)
        function obj = <MSGNAME>Message
            obj.m_data = zeros(MSG_SIZE, 'uint8');
            <INIT_CODE>
        end
    end
    methods
        <ACCESSORS>
    end
end