/*
    Created from:
        Messages = <INPUTFILENAME>
        Template = <TEMPLATEFILENAME>
        Language = <LANGUAGEFILENAME>

                     AUTOGENERATED FILE, DO NOT EDIT

*/

#include "<OUTPUTFILENAME>.h"


// include the C++ header file
//#include</path/to/cpp/<OUTPUTFILENAME>>


void <MSGFULLNAME>Send(const <MSGFULLNAME>Unpacked* unpackedMsg)
{
    // TODO other parameters needed here?
    uint8_t *data = allocate_msg(<MSGFULLNAME>_MSG_ID, <MSGFULLNAME>_MSG_SIZE);
    <SETFIELDS>
    send_msg(data);
    // TODO free data?
}


void <MSGFULLNAME>Receive(<MSGFULLNAME>Unpacked* unpackedMsg)
{
    // TODO other parameters needed here?
    uint8_t* data = message_rx_data(<MSGFULLNAME>_MSG_ID);
    if (!data) return;
    <GETFIELDS>
    // TODO free data?
}

#endif
