/*
    Created from:
        Messages = <INPUTFILENAME>
        Template = <TEMPLATEFILENAME>
        Language = <LANGUAGEFILENAME>

                     AUTOGENERATED FILE, DO NOT EDIT

*/
#include <memory>
// include the SimulinkStructs generated header
//#include "<OUTPUTFILENAME>.h"


// include the C++ header file
//#include</path/to/cpp/<OUTPUTFILENAME>>


void <MSGFULLNAME>Send(const <MSGFULLNAME>Unpacked* unpackedMsg)
{
    // TODO other parameters needed here?
    auto msg = std::make_unique<<MSGFULLNAME>Message>();
    <SETFIELDS>
    //sendMessage(std::move(msg));
}


void <MSGFULLNAME>Receive(<MSGFULLNAME>Unpacked* unpackedMsg)
{
    // TODO other parameters needed here?
    //auto msg = receiveMessage(<MSGFULLNAME>Message::MSG_ID);
    <MSGFULLNAME>Message *msg = nullptr;
    if (!msg) return;
    <GETFIELDS>
}
