/*
    Created from:
        Messages = <INPUTFILENAME>
        Template = <TEMPLATEFILENAME>
        Language = <LANGUAGEFILENAME>

                     AUTOGENERATED FILE, DO NOT EDIT

*/
#ifndef <MSGFULLNAME>Struct_H__
#define <MSGFULLNAME>Struct_H__

#include <stdint.h>

// This is for creating structs that correspond to messages,
// copying messages into and out of structs.


<ENUMERATIONS>


typedef struct
{
    <DECLARATIONS>
} <MSGFULLNAME>Struct;

void <MSGFULLNAME>Send(const <MSGFULLNAME>Struct* unpackedMsg);
void <MSGFULLNAME>Receive(<MSGFULLNAME>Struct* unpackedMsg);

<ONCE>#define <ESCAPED_INPUT_FILENAME>_FILE_HASH <INPUT_FILE_HASH_BYTES>

#endif
