/*
    Created from:
        Messages = <INPUTFILENAME>
        Template = <TEMPLATEFILENAME>
        Language = <LANGUAGEFILENAME>

                     AUTOGENERATED FILE, DO NOT EDIT

*/
#ifndef <MSGFULLNAME>Struct_H__
#define <MSGFULLNAME>Struct_H__

// This is for creating structs that correspond to messages,
// copying messages into and out of structs.

typedef struct
{
    <DECLARATIONS>
} <MSGFULLNAME>Struct;

void <MSGFULLNAME>UnpackFromMessage(uint8_t* m_data, <MSGFULLNAME>Struct* s)
{
    <STRUCTUNPACKING>
}
void <MSGFULLNAME>PackIntoMessage(uint8_t* m_data, <MSGFULLNAME>Struct* s)
{
    <STRUCTPACKING>
}

<ONCE>#define <ESCAPED_INPUT_FILENAME>_FILE_HASH <INPUT_FILE_HASH_BYTES>

#endif
