/*
    <OUTPUTFILENAME>
    Created <DATE> from:
        Messages = <INPUTFILENAME>
        Template = <TEMPLATEFILENAME>
        Language = <LANGUAGEFILENAME>

                     AUTOGENERATED FILE, DO NOT EDIT

*/
import java.nio.ByteBuffer;
import java.util.HashMap;
import java.util.Map;

class <MSGNAME>
{
    static final int SIZE = <MSGSIZE>;
    <MSGNAME>()
    {
        m_data = ByteBuffer.allocate(SIZE);
        Init();
    }
    <MSGNAME>(ByteBuffer buffer)
    {
        m_data = buffer;
    }
    void Init()
    {
        <INIT_CODE>
    }
    <ENUMERATIONS>
    <FIELDINFOS>
    void SetMessageID(int id)
    {
        <SETMSGID>;
    }
    int GetMessageID()
    {
        return <GETMSGID>;
    }
    <ACCESSORS>
    private ByteBuffer m_data;
};
