/*
    <OUTPUTFILENAME>
    Created <DATE> from:
        Messages = <INPUTFILENAME>
        Template = <TEMPLATEFILENAME>
        Language = <LANGUAGEFILENAME>

                     AUTOGENERATED FILE, DO NOT EDIT

*/
import java.nio.ByteBuffer;
import java.util.HashMap;
import java.util.Map;

class <MSGNAME>Message extends Message
{
    static final long MSG_ID = <MSGID>;
    static final int MSG_SIZE = <MSGSIZE>;
    <MSGNAME>Message()
    {
        super(MSG_SIZE);
        SetMessageID(MSG_ID);
        InitializeTime();
        Init();
    }
    <MSGNAME>Message(ByteBuffer buffer)
    {
        super(buffer);
    }
    void Init()
    {
        <INIT_CODE>
    }
    <ENUMERATIONS>
    <FIELDINFOS>
    <ACCESSORS>

    static boolean firstTimeReflection = true;
    static MsgInfo msgInfo;
    static MsgInfo ReflectionInfo()
    {
        if(firstTimeReflection)
        {
            msgInfo = new MsgInfo(MSG_ID, "<MSGNAME>", "<MSGDESCRIPTION>", MSG_SIZE);
            msgInfo.AddField(new <REFLECTION>);
            firstTimeReflection = false;
        }
        return msgInfo;
    }
};
