/*
    <OUTPUTFILENAME>
    Created <DATE> from:
        Messages = <INPUTFILENAME>
        Template = <TEMPLATEFILENAME>
        Language = <LANGUAGEFILENAME>

                     AUTOGENERATED FILE, DO NOT EDIT

*/
package Messages;

import java.nio.ByteBuffer;
import java.util.HashMap;
import java.util.Map;
import MsgApp.*;

public class <MSGNAME> extends Message
{
    public static final int MSG_ID = <MSGID>;
    public static final int MSG_SIZE = <MSGSIZE>;
    public <MSGNAME>()
    {
        super(MSG_SIZE);
        SetMessageID(MSG_ID);
        //InitializeTime();
        Init();
    }
    public <MSGNAME>(ByteBuffer buffer)
    {
        super(buffer);
    }
    void Init()
    {
        <INIT_CODE>
    }
    <ENUMERATIONS>
    <FIELDINFOS>
    <ACCESSORS>

    static boolean firstTimeReflection = true;
    static MsgInfo msgInfo;
    public static MsgInfo ReflectionInfo()
    {
        if(firstTimeReflection)
        {
            msgInfo = new MsgInfo(MSG_ID, "<MSGNAME>", "<MSGDESCRIPTION>", MSG_SIZE);
            msgInfo.AddField(new <REFLECTION>);
            firstTimeReflection = false;
        }
        return msgInfo;
    }
};
