/*
    <OUTPUTFILENAME>
    Created <DATE> from:
        Messages = <INPUTFILENAME>
        Template = <TEMPLATEFILENAME>
        Language = <LANGUAGEFILENAME>

                     AUTOGENERATED FILE, DO NOT EDIT

*/
//import { NetworkHeader } from '../headers/NetworkHeader.js'
//import MessageDictionary from '../MessageDictionary.js'

var <MSGSHORTNAME> = function(buffer) {
    // have baseclass construct the buffer?
    //Message.call(this, MSG_SIZE);
        
    if (buffer==undefined)
    {
        buffer = new ArrayBuffer(NetworkHeader.prototype.MSG_SIZE+<MSGSHORTNAME>.prototype.MSG_SIZE);
        this.m_data = new DataView(buffer, NetworkHeader.prototype.MSG_SIZE);
        this.hdr = new NetworkHeader(buffer);
        this.hdr.SetMessageID(<MSGSHORTNAME>.prototype.MSG_ID);
        this.hdr.SetDataLength(buffer.byteLength - NetworkHeader.prototype.MSG_SIZE);
        //this.InitializeTime();
        this.Init();
    }
    else
    {
        this.m_data = new DataView(buffer, NetworkHeader.prototype.MSG_SIZE);
        this.hdr = new NetworkHeader(buffer);
    }
};

// how to make constants?
<MSGSHORTNAME>.prototype.MSG_ID = <MSGID>;
<MSGSHORTNAME>.prototype.MSG_SIZE = <MSGSIZE>;
<MSGSHORTNAME>.prototype.MSG_NAME = "<MSGDESCRIPTOR>";

<MSGSHORTNAME>.prototype.MsgName = function(){
    return "<MSGDESCRIPTOR>";
}

msgtools.registerMessage(<MSGID>,<MSGSHORTNAME>)

<MSGSHORTNAME>.prototype.Init = function(){
    <INIT_CODE>
};


// http://stackoverflow.com/a/130572
<ENUMERATIONS>
<ACCESSORS>

// Convert to a javascript object
<MSGSHORTNAME>.prototype.toObject = function(){
    ret = {};
    <STRUCTUNPACKING>
    return ret;
}

// Reflection information
<MSGSHORTNAME>.prototype.fields = [
    <REFLECTION>
]

// for react-native and node.js, we should set module.exports so our class can be accessed externally
if(typeof module != 'undefined' && typeof module.exports != 'undefined')
    module.exports.<MSGSHORTNAME> = <MSGSHORTNAME>;
