/*
    /Users/mosminer/Projects/obj/CodeGenerator/Java/headers/NetworkHeader.java
    Created 16/11/2017 at 08:02:48 from:
        Messages = messages/headers/NetworkHeader.yaml
        Template = ../Java/JavaHeaderTemplate.java
        Language = ../Java/language.py

                     AUTOGENERATED FILE, DO NOT EDIT

*/
package headers;

import java.nio.ByteBuffer;
import java.util.HashMap;
import java.util.Map;

public class NetworkHeader
{
    public static final int SIZE = 16;
    public NetworkHeader()
    {
        m_data = ByteBuffer.allocate(SIZE);
        Init();
    }
    public NetworkHeader(ByteBuffer buffer)
    {
        m_data = buffer;
    }
    void Init()
    {
        SetSource(0);
        SetDestination(0);
        SetID(0);
        SetPriority(0);
        SetDataLength(0);
        SetTime(0);
    }
    public ByteBuffer GetBuffer()
    {
        return m_data;
    }
    class SourceFieldInfo {
        static final int loc   = 0;
        static final int max   = 65535;
        static final int min   = 0;
        static final String units = "";
        static final int count = 1;
        static final int defaultValue = 0;
    };
    
    class DestinationFieldInfo {
        static final int loc   = 2;
        static final int max   = 65535;
        static final int min   = 0;
        static final String units = "";
        static final int count = 1;
        static final int defaultValue = 0;
    };
    
    class IDFieldInfo {
        static final int loc   = 4;
        static final long max   = 4294967295L;
        static final long min   = 0;
        static final String units = "";
        static final int count = 1;
        static final long defaultValue = 0;
    };
    
    class PackedFieldFieldInfo {
        static final int loc   = 8;
        static final long max   = 4294967295L;
        static final long min   = 0;
        static final String units = "";
        static final int count = 1;
    };
    
    class PriorityFieldInfo {
        static final int loc   = 8;
        static final long max   = 255;
        static final long min   = 0;
        static final String units = "";
        static final int count = 1;
        static final long defaultValue = 0;
        static final int bitOffset = 0;
        static final int numBits   = 8;
    };
    
    class DataLengthFieldInfo {
        static final int loc   = 8;
        static final long max   = 16777215;
        static final long min   = 0;
        static final String units = "";
        static final int count = 1;
        static final long defaultValue = 0;
        static final int bitOffset = 8;
        static final int numBits   = 24;
    };
    
    class TimeFieldInfo {
        static final int loc   = 12;
        static final long max   = 4294967295L;
        static final long min   = 0;
        static final String units = "";
        static final int count = 1;
        static final long defaultValue = 0;
    };
    
    public void SetMessageID(long id)
    {
        SetID((long)(id & 0xffffffff));
    }
    public long GetMessageID()
    {
        return GetID();
    }
    //  , (0 to 65535)
    public int GetSource()
    {
        return toUnsignedInt(m_data.getShort(0));
    }
    //  , (0 to 65535)
    public int GetDestination()
    {
        return toUnsignedInt(m_data.getShort(2));
    }
    //  , (0 to 4294967295)
    public long GetID()
    {
        return toUnsignedLong(m_data.getInt(4));
    }
    // To hold bitfields , (0 to 4294967295)
    public long GetPackedField()
    {
        return toUnsignedLong(m_data.getInt(8));
    }
    //  , (0 to 255)
    public long GetPriority()
    {
        return (long)((GetPackedField() >> 0) & 0xff);
    }
    //  , (0 to 16777215)
    public long GetDataLength()
    {
        return (long)((GetPackedField() >> 8) & 0xffffff);
    }
    // Rolling millisecond counter. , (0 to 4294967295)
    public long GetTime()
    {
        return toUnsignedLong(m_data.getInt(12));
    }
    //  , (0 to 65535)
    public void SetSource(int value)
    {
        m_data.putShort(0, (short)value);
    }
    //  , (0 to 65535)
    public void SetDestination(int value)
    {
        m_data.putShort(2, (short)value);
    }
    //  , (0 to 4294967295)
    public void SetID(long value)
    {
        m_data.putInt(4, (int)value);
    }
    // To hold bitfields , (0 to 4294967295)
    public void SetPackedField(long value)
    {
        m_data.putInt(8, (int)value);
    }
    //  , (0 to 255)
    public void SetPriority(long value)
    {
        SetPackedField((long)((GetPackedField() & ~(0xff << 0)) | ((value & 0xff) << 0)));
    }
    //  , (0 to 16777215)
    public void SetDataLength(long value)
    {
        SetPackedField((long)((GetPackedField() & ~(0xffffff << 8)) | ((value & 0xffffff) << 8)));
    }
    // Rolling millisecond counter. , (0 to 4294967295)
    public void SetTime(long value)
    {
        m_data.putInt(12, (int)value);
    }
    private ByteBuffer m_data;

    private static int toUnsignedInt(short s) {
        return 0x0000FFFF & s;
    }

    private static long toUnsignedLong(int i) {
        return 0x00000000FFFFFFFFL & i;
    }
};
