/*
    /Users/mosminer/Projects/obj/CodeGenerator/Java/headers/SerialHeader.java
    Created 16/11/2017 at 08:02:48 from:
        Messages = messages/headers/SerialHeader.yaml
        Template = ../Java/JavaHeaderTemplate.java
        Language = ../Java/language.py

                     AUTOGENERATED FILE, DO NOT EDIT

*/
package headers;

import java.nio.ByteBuffer;
import java.util.HashMap;
import java.util.Map;

public class SerialHeader
{
    public static final int SIZE = 16;
    public SerialHeader()
    {
        m_data = ByteBuffer.allocate(SIZE);
        Init();
    }
    public SerialHeader(ByteBuffer buffer)
    {
        m_data = buffer;
    }
    void Init()
    {
        SetStartSequence(3735928559L);
        SetID(0);
        SetFixedBitForMatlab(1);
        SetSource((short)0);
        SetDestination((short)0);
        SetPriority(0);
        SetDataLength(0);
        SetTime(0);
        SetHeaderChecksum(0);
        SetBodyChecksum(0);
    }
    class StartSequenceFieldInfo {
        static final int loc   = 0;
        static final long max   = 4294967295L;
        static final long min   = 0;
        static final String units = "";
        static final int count = 1;
        static final long defaultValue = 3735928559L;
    };
    
    class PackedField1FieldInfo {
        static final int loc   = 4;
        static final int max   = 65535;
        static final int min   = 0;
        static final String units = "";
        static final int count = 1;
    };
    
    class IDFieldInfo {
        static final int loc   = 4;
        static final int max   = 32767;
        static final int min   = 0;
        static final String units = "";
        static final int count = 1;
        static final int defaultValue = 0;
        static final int bitOffset = 0;
        static final int numBits   = 15;
    };
    
    class FixedBitForMatlabFieldInfo {
        static final int loc   = 4;
        static final int max   = 1;
        static final int min   = 0;
        static final String units = "";
        static final int count = 1;
        static final int defaultValue = 1;
        static final int bitOffset = 15;
        static final int numBits   = 1;
    };
    
    class SourceFieldInfo {
        static final int loc   = 6;
        static final short max   = 255;
        static final short min   = 0;
        static final String units = "";
        static final int count = 1;
        static final short defaultValue = 0;
    };
    
    class DestinationFieldInfo {
        static final int loc   = 7;
        static final short max   = 255;
        static final short min   = 0;
        static final String units = "";
        static final int count = 1;
        static final short defaultValue = 0;
    };
    
    class PackedField2FieldInfo {
        static final int loc   = 8;
        static final int max   = 65535;
        static final int min   = 0;
        static final String units = "";
        static final int count = 1;
    };
    
    class PriorityFieldInfo {
        static final int loc   = 8;
        static final int max   = 3;
        static final int min   = 0;
        static final String units = "";
        static final int count = 1;
        static final int defaultValue = 0;
        static final int bitOffset = 0;
        static final int numBits   = 2;
    };
    
    class DataLengthFieldInfo {
        static final int loc   = 8;
        static final int max   = 16383;
        static final int min   = 0;
        static final String units = "";
        static final int count = 1;
        static final int defaultValue = 0;
        static final int bitOffset = 2;
        static final int numBits   = 14;
    };
    
    class TimeFieldInfo {
        static final int loc   = 10;
        static final int max   = 65535;
        static final int min   = 0;
        static final String units = "";
        static final int count = 1;
        static final int defaultValue = 0;
    };
    
    class HeaderChecksumFieldInfo {
        static final int loc   = 12;
        static final int max   = 65535;
        static final int min   = 0;
        static final String units = "";
        static final int count = 1;
        static final int defaultValue = 0;
    };
    
    class BodyChecksumFieldInfo {
        static final int loc   = 14;
        static final int max   = 65535;
        static final int min   = 0;
        static final String units = "";
        static final int count = 1;
        static final int defaultValue = 0;
    };
    
    public void SetMessageID(int id)
    {
        SetID((int)(id & 0x7fff));
    }
    public int GetMessageID()
    {
        return GetID();
    }
    //  , (0 to 4294967295)
    public long GetStartSequence()
    {
        return (long)Integer.toUnsignedLong(m_data.getInt(0));
    }
    // To hold bitfields , (0 to 65535)
    public int GetPackedField1()
    {
        return (int)Short.toUnsignedInt(m_data.getShort(4));
    }
    //  , (0 to 32767)
    public int GetID()
    {
        return (int)((GetPackedField1() >> 0) & 0x7fff);
    }
    //  , (0 to 1)
    public int GetFixedBitForMatlab()
    {
        return (int)((GetPackedField1() >> 15) & 0x1);
    }
    //  , (0 to 255)
    public short GetSource()
    {
        return (short)Byte.toUnsignedInt(m_data.get(6));
    }
    //  , (0 to 255)
    public short GetDestination()
    {
        return (short)Byte.toUnsignedInt(m_data.get(7));
    }
    // To hold bitfields , (0 to 65535)
    public int GetPackedField2()
    {
        return (int)Short.toUnsignedInt(m_data.getShort(8));
    }
    //  , (0 to 3)
    public int GetPriority()
    {
        return (int)((GetPackedField2() >> 0) & 0x3);
    }
    //  , (0 to 16383)
    public int GetDataLength()
    {
        return (int)((GetPackedField2() >> 2) & 0x3fff);
    }
    // Rolling millisecond counter. , (0 to 65535)
    public int GetTime()
    {
        return (int)Short.toUnsignedInt(m_data.getShort(10));
    }
    //  , (0 to 65535)
    public int GetHeaderChecksum()
    {
        return (int)Short.toUnsignedInt(m_data.getShort(12));
    }
    //  , (0 to 65535)
    public int GetBodyChecksum()
    {
        return (int)Short.toUnsignedInt(m_data.getShort(14));
    }
    //  , (0 to 4294967295)
    public void SetStartSequence(long value)
    {
        m_data.putInt(0, (int)value);
    }
    // To hold bitfields , (0 to 65535)
    public void SetPackedField1(int value)
    {
        m_data.putShort(4, (short)value);
    }
    //  , (0 to 32767)
    public void SetID(int value)
    {
        SetPackedField1((int)((GetPackedField1() & ~(0x7fff << 0)) | ((value & 0x7fff) << 0)));
    }
    //  , (0 to 1)
    public void SetFixedBitForMatlab(int value)
    {
        SetPackedField1((int)((GetPackedField1() & ~(0x1 << 15)) | ((value & 0x1) << 15)));
    }
    //  , (0 to 255)
    public void SetSource(short value)
    {
        m_data.put(6, (byte)value);
    }
    //  , (0 to 255)
    public void SetDestination(short value)
    {
        m_data.put(7, (byte)value);
    }
    // To hold bitfields , (0 to 65535)
    public void SetPackedField2(int value)
    {
        m_data.putShort(8, (short)value);
    }
    //  , (0 to 3)
    public void SetPriority(int value)
    {
        SetPackedField2((int)((GetPackedField2() & ~(0x3 << 0)) | ((value & 0x3) << 0)));
    }
    //  , (0 to 16383)
    public void SetDataLength(int value)
    {
        SetPackedField2((int)((GetPackedField2() & ~(0x3fff << 2)) | ((value & 0x3fff) << 2)));
    }
    // Rolling millisecond counter. , (0 to 65535)
    public void SetTime(int value)
    {
        m_data.putShort(10, (short)value);
    }
    //  , (0 to 65535)
    public void SetHeaderChecksum(int value)
    {
        m_data.putShort(12, (short)value);
    }
    //  , (0 to 65535)
    public void SetBodyChecksum(int value)
    {
        m_data.putShort(14, (short)value);
    }
    private ByteBuffer m_data;
};
