/*
    Created from:
        Messages = <INPUTFILENAME>
        Template = <TEMPLATEFILENAME>
        Language = <LANGUAGEFILENAME>

                     AUTOGENERATED FILE, DO NOT EDIT

*/
#ifndef <MSGNAME>Code_H__
#define <MSGNAME>Code_H__

#define <MSGNAME>_MSG_ID <MSGID>
#define <MSGNAME>_MSG_SIZE <MSGSIZE>
<ENUMERATIONS>
<FIELDINFOS>
<ACCESSORS>
INLINE void <MSGNAME>_Init(uint8_t* m_data)
{
    <INIT_CODE>
}

#endif
