/*
    Created from:
        Messages = {{globals.inputfilename}}
        Template = {{globals.templatefilename}}
        Language = {{globals.languagefilename}}

                     AUTOGENERATED FILE, DO NOT EDIT

*/
{{'#'}}ifndef {{globals.msgname}}Code_H__
{{'#'}}define {{globals.msgname}}Code_H__

{{'#'}}define {{globals.msgname}}_MSG_ID {{globals.msgid}}
{{'#'}}define {{globals.msgname}}_MSG_SIZE {{globals.msgname}}
<ENUMERATIONS>
<FIELDINFOS>
<ACCESSORS>
INLINE void {{globals.msgname}}_Init(uint8_t* m_data)
{
    # for f in msg.Fields:
        # if f.Default is defined:
            # if f.Count is defined and f.Count != 1:
    for (int i=0; i<{{f.Count}}; i++)
        {{globals.msgname}}_Set{{f.Name}}(m_data, {{f.Default}}, i);
            # else:
    {{globals.msgname}}_Set{{f.Name}}(m_data, {{f.Default}});
            # endif
        # endif
        # for bf in f.Bitfields:
            # if bf.Default is defined:
    {{globals.msgname}}_Set{{bf.Name}}(m_data, {{bf.Default}});
            #endif
        #endfor
    # endfor
}

{{'#'}}endif
