/*
    /Users/mosminer/Projects/obj/CodeGenerator/Java/Network/MaskedSubscription.java
    Created 16/11/2017 at 08:02:48 from:
        Messages = messages/Network/MaskedSubscription.yaml
        Template = ../Java/JavaTemplate.java
        Language = ../Java/language.py

                     AUTOGENERATED FILE, DO NOT EDIT

*/
package Network;

import java.nio.ByteBuffer;
import java.util.HashMap;
import java.util.Map;
import MsgApp.*;

public class MaskedSubscription extends Message
{
    public static final int MSG_ID = (int)4294967043L;
    public static final int MSG_SIZE = 8;
    public MaskedSubscription()
    {
        super(MSG_SIZE);
        SetMessageID(MSG_ID);
        //InitializeTime();
        Init();
    }
    public MaskedSubscription(ByteBuffer buffer)
    {
        super(buffer);
    }
    void Init()
    {
    }
    class MaskFieldInfo {
        static final int loc   = 0;
        static final long max   = 4294967295L;
        static final long min   = 0;
        static final String units = "";
        static final int count = 1;
    };
    
    class ValueFieldInfo {
        static final int loc   = 4;
        static final long max   = 4294967295L;
        static final long min   = 0;
        static final String units = "";
        static final int count = 1;
    };
    
    // The mask of the ID you'd like to receive.  0=Don't care, 1=Must match. , (0 to 4294967295)
    public long GetMask()
    {
        return (long)Integer.toUnsignedLong(m_data.getInt(0));
    }
    // The value of the ID you'd like to receive. , (0 to 4294967295)
    public long GetValue()
    {
        return (long)Integer.toUnsignedLong(m_data.getInt(4));
    }
    // The mask of the ID you'd like to receive.  0=Don't care, 1=Must match. , (0 to 4294967295)
    public void SetMask(long value)
    {
        m_data.putInt(0, (int)value);
    }
    // The value of the ID you'd like to receive. , (0 to 4294967295)
    public void SetValue(long value)
    {
        m_data.putInt(4, (int)value);
    }

    public static MsgInfo msgInfo;
    static
    {
        msgInfo = new MsgInfo(MaskedSubscription.class, MSG_ID, "A subscription mask and value.", MSG_SIZE);
        msgInfo.AddField(new FieldInfo("Mask", "The mask of the ID you'd like to receive.  0=Don't care, 1=Must match.", "", 1));
        msgInfo.AddField(new FieldInfo("Value", "The value of the ID you'd like to receive.", "", 1));
    }
};
