/*
    /Users/mosminer/Projects/obj/CodeGenerator/Java/Network/SubscriptionList.java
    Created 16/11/2017 at 08:02:48 from:
        Messages = messages/Network/SubscriptionList.yaml
        Template = ../Java/JavaTemplate.java
        Language = ../Java/language.py

                     AUTOGENERATED FILE, DO NOT EDIT

*/
package Network;

import java.nio.ByteBuffer;
import java.util.HashMap;
import java.util.Map;
import MsgApp.*;

public class SubscriptionList extends Message
{
    public static final int MSG_ID = (int)4294967042L;
    public static final int MSG_SIZE = 64;
    public SubscriptionList()
    {
        super(MSG_SIZE);
        SetMessageID(MSG_ID);
        //InitializeTime();
        Init();
    }
    public SubscriptionList(ByteBuffer buffer)
    {
        super(buffer);
    }
    void Init()
    {
    }
    class IDsFieldInfo {
        static final int loc   = 0;
        static final long max   = 4294967295L;
        static final long min   = 0;
        static final String units = "";
        static final int count = 16;
    };
    
    // The IDs of the messages you'd like to receive. , (0 to 4294967295)
    public long GetIDs(int idx)
    {
        return (long)Integer.toUnsignedLong(m_data.getInt(0+idx*4));
    }
    // The IDs of the messages you'd like to receive. , (0 to 4294967295)
    public void SetIDs(long value, int idx)
    {
        m_data.putInt(0+idx*4, (int)value);
    }

    public static MsgInfo msgInfo;
    static
    {
        msgInfo = new MsgInfo(SubscriptionList.class, MSG_ID, "A list of subscriptions.", MSG_SIZE);
        msgInfo.AddField(new FieldInfo("IDs", "The IDs of the messages you'd like to receive.", "", 16));
    }
};
