/*
    <OUTPUTFILENAME>
    Created <DATE> from:
        Messages = <INPUTFILENAME>
        Template = <TEMPLATEFILENAME>
        Language = <LANGUAGEFILENAME>

                     AUTOGENERATED FILE, DO NOT EDIT

*/
#include <stdint.h>

#ifndef <MSGNAME>_H__
#define <MSGNAME>_H__

class <MSGNAME>
{
    public:
        enum { SIZE = <MSGSIZE> };
        <MSGNAME>()
        {
            Init();
        }
        void Init()
        {
            <INIT_CODE>
        }
        <ENUMERATIONS>
        <ACCESSORS>
    private:
        uint8_t m_data[SIZE];
};

#endif
