/*
    <OUTPUTFILENAME>
    Created <DATE> from:
        Messages = <INPUTFILENAME>
        Template = <TEMPLATEFILENAME>
        Language = <LANGUAGEFILENAME>

                     AUTOGENERATED FILE, DO NOT EDIT

*/
#ifndef <MSGNAME>_H__
#define <MSGNAME>_H__

#include <stdint.h>
#include <cfloat>
#include "FieldAccess.h"

class <MSGNAME>
{
    public:
        auto static constexpr SIZE = <MSGSIZE>;
        <MSGNAME>()
        {
            Init();
        }
        void Init()
        {
            <INIT_CODE>
        }
        <ENUMERATIONS>
        <FIELDINFOS>
        <ACCESSORS>
    private:
        uint8_t m_data[SIZE];
};

#endif
