/*
    <OUTPUTFILENAME>
    Created <DATE> from:
        Messages = <INPUTFILENAME>
        Template = <TEMPLATEFILENAME>
        Language = <LANGUAGEFILENAME>

                     AUTOGENERATED FILE, DO NOT EDIT

*/
#ifndef <MSGNAME>Message_H__
#define <MSGNAME>Message_H__

#include <stdint.h>
#include "FieldAccess.h"

class <MSGNAME>Message : public Message
{
    public:
        enum { MSG_ID = <MSGID>};
        enum { MSG_SIZE = <MSGSIZE> };
        <MSGNAME>Message(int size=MSG_SIZE)
        : Message(size)
        {
            if(Exists())
            {
                SetPayloadLength(size);
                SetMessageID(MSG_ID);
                Init();
            }
        }
        void Init()
        {
            <INIT_CODE>
        }
        <ENUMERATIONS>
        <ACCESSORS>
        static MsgInfo* ReflectionInfo()
        {
            static bool firstTime = true;
            static MsgInfo msgInfo(MSG_ID, "<MSGNAME>", "<MSGDESCRIPTION>", MSG_SIZE);
            if(firstTime)
            {
                msgInfo.AddField(new <REFLECTION>);
            }
            return &msgInfo;
        }
};

#endif
