/*
    <OUTPUTFILENAME>
    Created <DATE> from:
        Messages = <INPUTFILENAME>
        Template = <TEMPLATEFILENAME>
        Language = <LANGUAGEFILENAME>

                     AUTOGENERATED FILE, DO NOT EDIT

*/
#ifndef <MSGNAME>Code_H__
#define <MSGNAME>Code_H__

#include <stdint.h>

const uint32_t <MSGNAME>_MSG_ID = <MSGID>;
const int <MSGNAME>_MSG_SIZE = <MSGSIZE>;
<ENUMERATIONS>
<ACCESSORS>
void <MSGNAME>_Init(uint8_t* m_data)
{
    <INIT_CODE>
}

#endif
