/*
    <OUTPUTFILENAME>
    Created <DATE> from:
        Messages = <INPUTFILENAME>
        Template = <TEMPLATEFILENAME>
        Language = <LANGUAGEFILENAME>

                     AUTOGENERATED FILE, DO NOT EDIT

*/
open class <MSGNAME>
{
    open let MSG_SIZE = <MSGSIZE>;
    open let MSG_NAME = "<MSGDESCRIPTOR>";
    
    open func init()
    {
        buffer = new ArrayBuffer(MSG_SIZE);
        m_data = new DataView(buffer);
        Init();
    }
    open func init(buffer: bytearray)
    {
        m_data = new DataView(buffer);
    }
    func Init()
    {
        <INIT_CODE>
    }

    open func SetMessageID(id: Int)
    {
        <SETMSGID>;
    };
    open func GetMessageID() -> Int
    {
        return <GETMSGID>;
    };

    <ENUMERATIONS>
    <ACCESSORS>
};
