/*
    <OUTPUTFILENAME>
    Created <DATE> from:
        Messages = <INPUTFILENAME>
        Template = <TEMPLATEFILENAME>
        Language = <LANGUAGEFILENAME>

                     AUTOGENERATED FILE, DO NOT EDIT

*/
public class <MSGNAME>
{
    public let MSG_SIZE = <MSGSIZE>;
    public let MSG_NAME = "<MSGDESCRIPTOR>";
    var m_data: NSMutableData;
    
    init()
    {
        m_data = NSMutableData(MSG_SIZE);
        Initialize();
    }
    init(buffer: NSMutableData)
    {
        m_data = NSMutableData(MSG_SIZE);
    }
    func Initialize()
    {
        <INIT_CODE>
    }

    public func SetMessageID(_ id: Int)
    {
        <SETMSGID>;
    };
    public func GetMessageID() -> Int
    {
        return <GETMSGID>;
    };

    <ENUMERATIONS>
    <ACCESSORS>
};
