/*
    <OUTPUTFILENAME>
    Created <DATE> from:
        Messages = <INPUTFILENAME>
        Template = <TEMPLATEFILENAME>
        Language = <LANGUAGEFILENAME>

                     AUTOGENERATED FILE, DO NOT EDIT

*/
public class <MSGNAME>
{
    public let MSG_ID = <MSGID>;
    public let MSG_SIZE = <MSGSIZE>;
    public let MSG_NAME = "<MSGDESCRIPTOR>";
    var hdr: NetworkHeader;
    var m_data: NSMutableData;
    init()
    {
        m_data = NSMutableData(buffer, NetworkHeader.MSG_SIZE);
        hdr = NetworkHeader(buffer);
        hdr.SetMessageID(MSG_ID);
        hdr.SetDataLength(buffer.byteLength - NetworkHeader.MSG_SIZE);
        //InitializeTime();
        Initialize();
    }
    init(buffer: NSMutableData)
    {
        m_data = buffer;
        hdr = NetworkHeader(buffer);
    }
    func Initialize()
    {
        <INIT_CODE>
    }

    <ENUMERATIONS>
    <ACCESSORS>

    // Reflection information
    public let fields = [
        <REFLECTION>
    ]
};

// add our class to the dictionary
//MessageDictionary[<MSGID>] = <MSGNAME>;
